spring:
  application:
    name: test-task
  datasource:
    url: jdbc:postgresql://localhost:5432/test_task
    username: postgres
    password: qwerty12345
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: TRACE
    com.secureuser.service.model.listener: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8